server:
  port: 8081
management.server.port: 8091
management.server.address: 127.0.0.1

management:
  endpoints:
    web:
      exposure:
        include:
          - "mappings"
          - "info"
          - "health"
          - "httptrace"
      base-path: "/system"
  endpoint:
    health:
      enabled: true
      show-details: always